# Generated by Django 6.0.2 on 2026-03-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_expense", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
