# Generated by Django 6.0.2 on 2026-03-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_expense", "0003_groupinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="last_reminded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
