# Generated by Django 6.0.2 on 2026-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_expense", "0004_groupmember_last_reminded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="reminders_sent_today",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
