# Generated by Django 6.0.2 on 2026-05-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_expense", "0006_externalfriendinvitation_friendrequest_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="local_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="local_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="settlement",
            name="local_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
