# Generated by Django 6.0.2 on 2026-05-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_expense", "0007_expense_local_id_group_local_id_settlement_local_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="color",
            field=models.CharField(default="#C8E64A", max_length=20),
        ),
        migrations.AddField(
            model_name="group",
            name="icon",
            field=models.CharField(default="groups", max_length=50),
        ),
    ]
