# Generated by Django 6.0.2 on 2026-08-22 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_expense", "0010_groupmember_invited_by_alter_group_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="invite_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="members_can_invite",
            field=models.BooleanField(default=True),
        ),
    ]
