# Generated by Django 6.0.2 on 2026-08-22 18:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_expense", "0011_group_invite_token_group_members_can_invite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="invite_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
