# Generated by Django 5.2.15 on 2026-09-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_code",
                    models.IntegerField(
                        help_text="The internal build number (e.g., 1)"
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="The display version (e.g., 1.0.0)", max_length=50
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="If true, users must update to continue using the app",
                    ),
                ),
                (
                    "release_notes",
                    models.TextField(
                        blank=True, help_text="What's new in this version"
                    ),
                ),
                (
                    "update_url",
                    models.URLField(help_text="The URL to download the new version"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only the active version with the highest version_code is returned to the app",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version_code"],
            },
        ),
    ]
