# Generated by Django 5.2.15 on 2026-09-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_appversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appversion",
            name="release_notes",
            field=models.TextField(
                blank=True,
                default="Bug fixes and performance improvements.",
                help_text="What's new in this version",
            ),
        ),
        migrations.AlterField(
            model_name="appversion",
            name="update_url",
            field=models.URLField(
                default="https://espere.in/espere.apk",
                help_text="The URL to download the new version",
            ),
        ),
    ]
