"""Cache utility definitions for Montra."""
from django.core.cache import cache
from django.core.cache.utils import make_template_fragment_key
from django.utils import timezone

def invalidate_user_cache(user_id):
    """Invalidate all cached items for a specific user.
    Since we don't have Redis wildcard matching for DB cache,
    we explicitly delete known keys generated by {% cache %} tags.
    """
    keys_to_delete = [
        make_template_fragment_key("dashboard", [user_id]),
    ]
    
    # Invalidate reports across recent years
    current_year = timezone.now().year
    for year in range(current_year - 5, current_year + 2):
        keys_to_delete.append(make_template_fragment_key("reports", [user_id, year]))
        
    cache.delete_many(keys_to_delete)
