# Generated by Django 6.0.2 on 2026-02-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="show_hero_image",
            field=models.BooleanField(default=True),
        ),
    ]
