# Generated by Django 6.0.2 on 2026-03-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationtoken",
            name="attempt_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="emailverificationtoken",
            name="last_sent_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="attempt_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="last_sent_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
