# Generated by Django 6.0.2 on 2026-03-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailverificationtoken_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_reminders',
            field=models.BooleanField(default=True, help_text='Receive daily reminders to log expenses.'),
        ),
    ]
