# Generated by Django 6.0.2 on 2026-03-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_email_reminders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='show_hero_image',
        ),
    ]
