# Generated by Django 6.0.2 on 2026-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_remove_userprofile_show_hero_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                    ("INR", "Indian Rupee (₹)"),
                    ("JPY", "Japanese Yen (¥)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("AUD", "Australian Dollar (A$)"),
                    ("PKR", "Pakistani Rupee (Rs)"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
    ]
