# Generated by Django 6.0.2 on 2026-06-20 06:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.CharField(default=accounts.models.generate_otp, max_length=6),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(default=accounts.models.generate_otp, max_length=6),
        ),
    ]
