# Generated by Django 6.0.2 on 2026-02-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(default="category", max_length=30),
        ),
    ]
