# Generated by Django 6.0.2 on 2026-02-15 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_alter_category_icon"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecurringTransaction",
        ),
    ]
