# Generated by Django 6.0.2 on 2026-02-15 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_delete_recurringtransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("savings", "Savings"),
                            ("flag", "Goal"),
                            ("home", "Home"),
                            ("flight", "Travel"),
                            ("school", "Education"),
                            ("directions_car", "Car"),
                            ("devices", "Tech"),
                            ("favorite", "Wishlist"),
                            ("emergency", "Emergency"),
                            ("diamond", "Luxury"),
                            ("volunteer_activism", "Charity"),
                        ],
                        default="savings",
                        max_length=30,
                    ),
                ),
                ("color", models.CharField(default="#26A69A", max_length=7)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_completed", "-created_at"],
            },
        ),
    ]
