# Generated by Django 6.0.2 on 2026-03-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0005_change_date_to_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(default="#C8E64A", max_length=7),
        ),
        migrations.AlterField(
            model_name="savingsgoal",
            name="color",
            field=models.CharField(default="#C8E64A", max_length=7),
        ),
    ]
