# Generated by Django 6.0.2 on 2026-05-12 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0006_alter_category_color_alter_savingsgoal_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="transactions.savingsgoal",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
