# Generated by Django 6.0.2 on 2026-05-12 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_savingstransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "category")},
        ),
        migrations.AlterField(
            model_name="budget",
            name="month",
            field=models.DateField(
                help_text="The month this budget was last updated or applies to"
            ),
        ),
    ]
