# Generated by Django 6.0.2 on 2026-08-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transactions",
            "0008_alter_budget_options_alter_budget_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default="expense",
                max_length=7,
            ),
        ),
    ]
