# Generated by Django 6.0.2 on 2026-08-07 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0009_category_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "category", "month")},
        ),
    ]
